
# This file exists to embed authorship and licensing data for
# all asset files the game uses. It also allows developers to
# rapidly identify new un-licensed or unattributed art via the
# ./scripts/media-licensing-report.py
# script.

[[license]]
file = 'very-poorly-drawn-character-designed-in-aseprite.aseprite'
license_spdx_id = 'GPL-2.0'
license_file = '/dev/null' # TODO someday we will need to keep actual copies of the relevant license text in here, this will point to the correct license file path.
author = 'Jeffrey McAteer'


[[license]]
file = 'stone_rock_or_wood_moved_no_tick.mp3'
license_spdx_id = 'CC0-1.0'
author = 'omegagreg'
source = 'https://opengameart.org/content/stonerockorwoodmovednotick'

[[license]]
file = 'broken-image.svg'
license_spdx_id = 'CC0-1.0'
author = 'AI'

[[license]]
file = 'Still_Life_Apples_and_Chestnuts_by_John_F_Francis.jpg'
license_spdx_id = 'CC0-1.0'
author = 'John F. Francis'
source = 'https://commons.wikimedia.org/wiki/File:Still_Life,_Apples_and_Chestnuts_LACMA_AC1994.152.4.jpg'

[[license]]
file = 'icon.svg'
license_spdx_id = 'CC0-1.0'
author = 'AI-generated'

[[license]]
file = 'view-of-the-natural-bridge-dc4df5.jpg'
license_spdx_id = 'CC0-1.0'
author = 'William James Bennett after Jacob C. Ward (1835)'
source = 'https://www.nga.gov/artworks/66535-view-natural-bridge'

[[license]]
file = 'main-menu-man-walks-into-forest.jpg'
license_spdx_id = 'CC0-1.0'
author = 'This was AI-generated by https://perchance.org/ai-text-to-image-generator'

[[license]]
file = 'main-menu-man-walks-into-forest.rainy.png'
license_spdx_id = 'CC0-1.0'
author = 'This was AI-generated by https://perchance.org/ai-text-to-image-generator'

[[license]]
file = 'main-menu-man-walks-into-forest.sunny.png'
license_spdx_id = 'CC0-1.0'
author = 'This was AI-generated by https://perchance.org/ai-text-to-image-generator'

[[license]]
file = 'main-menu-man-walks-into-forest.fall.png'
license_spdx_id = 'CC0-1.0'
author = 'This was AI-generated by https://perchance.org/ai-text-to-image-generator'


